ALTER TABLE machine_sales ADD COLUMN IF NOT EXISTS version BIGINT DEFAULT 0;
ALTER TABLE installments ADD COLUMN IF NOT EXISTS version BIGINT DEFAULT 0;
ALTER TABLE payments ADD COLUMN IF NOT EXISTS version BIGINT DEFAULT 0;
